### ISSUE TITLE
Can't get Xpadder to work with vjoy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Kytech/xbox360wirelesschatpad#46]
```
Running 64 bit Windows 7.
I read that you're currently working on a way to remap the gamepad buttons and 
for now to use xpadder, but I can't get any program to read the controller 
input. It will recognize the vjoy controller but won't take any input. 
Suggestions?


```

Original issue reported on code.google.com by `Steck.A...@gmail.com` on 5 Jul 2014 at 11:10

**Comment by KytechN24** [comment]
Try re-calibrating the controller in Windows, samuelst...@gmail.com.

**Comment by Kytech** [comment]
I have tested with Xpadder version 5.7 without issues using the vJoy version linked to in the README. An updated version of vJoy, and/or Xpadder may be needed. They may not like playing well if one is new and the other old. Issue #75 has information on setting this up with a newer version of vJoy. I plan to automate configuration of vJoy, which would be a good chance to update vJoy when I get there. As of now, the current fix that I will accept is to use an older version of Xpadder since it is known to work.
