### ISSUE TITLE
Libusp not compatible on windows 10/ 64 bits

### ISSUE THREAD

**Issue by Lauberhan** [Kytech/xbox360wirelesschatpad#72]
Intel version doesn't open even in compatibility mode, 32 bits version dosn't install because my windows is 64. Is there a alternative way/program?

**Comment by KytechN24** [comment]
LibUSB is available for both 32-bit and 64-bit Windows 10. There should be a 64-bit version included in the zip download. Since you computer is 64-bit, you need to install the 64-bit version which should be available for download [here.](https://sourceforge.net/projects/libusb-win32/files/libusb-win32-releases/1.2.6.0/libusb-win32-bin-1.2.6.0.zip/download) Inside the zip, browse to libusb-win32-bin-1.2.6.0 >> bin >> amd64 and run install-filter-win.exe. Make sure you run the version in the amd64 directory and not the ia64. ia64 is Intel's itanium architecture, which is typically only used by servers. 64-bit Windows refers to amd64 (x64).
