### ISSUE TITLE
SkyAg Available if Beneficial

### ISSUE THREAD

**Issue by ksbarnes** [Kytech/xbox360wirelesschatpad#78]
Not sure if there's a way to prove it, but I am SkyAg, the original guilty party for this code base on Google. :)

I abandoned the project many years ago as I quit FFXIV, my original reason for bringing the parent solutions findings together.

In any case, I've recently started playing FFXIV again, and was incredibly shocked to find this project still living on. While it's been a long time since the original work, and my own C# skills have grown rusty, I'm happy to help out wherever I can if it's useful!

Though, I'm still incredibly disappointed Microsoft has seemingly not released a 1st party driver to support this! It'd be so easy for them after all, the date is there.

**Comment by Kytech** [comment]
@ksbarnes Glad to hear from you! I remember trying to contact you back when the Google code shutdown originally occurred. I actually recognize your username based on the email you used with Google Code. I would love to pull you on this repo and just set you as a collaborator so that you have full access to this. Seeing as you are the original author, I would be happy to transfer ownership to you if you would prefer that.

I'm already pretty convinced that you're the original author, but just to be sure, do you have access to the original email you committed with when this was on Google Code? I could just send you an email there and if I get a response, that would be enough for me to confidently state that you are the original owner.

**Comment by Kytech** [comment]
I also noted that the domain you used with Google Code commits appears to redirect to a linkedin profile that seems to be you. I could also send you a connection request on LinkedIn and message you on linkedin to confirm you are the person who controlled that email and domain if you no longer have access to that original inbox. Either of those methods work for me.

**Comment by ksbarnes** [comment]
I just setup a redirect for what I think was the old email, so if you want to try that route it "should" work. Otherwise the LinkedIn route can work to.

As for owner, that's certainly not necessary at all. If you think I can help contribute then that can be enough. I'm really more in GitLab so I wouldn't really do much in GitHub as far as Owner is concerned anyway; and for all we know history will repeat itself and the project will get abandoned again. I'm just happy to see someone's gotten use out of thing.

**Comment by Kytech** [comment]
Sounds good. I'll send you an email at that address and I'll keep an eye out for a response from you.

**Comment by Kytech** [comment]
Seems like I had a bounce on the skyag.net email address, though I have a gmail address that I think I contacted you at a long time ago in the Google code days, so I also sent the email there. If you don't have access to that account, I'll just use the LinkedIn route.

**Comment by ksbarnes** [comment]
Got something from ya, replied. Go the LinkedIn route if you didn't get it! Closing this thread for now.
